// Currenlty relies on predfined data for quotes, books, and projects
// Could be improved by adding web scraping capabilities to pull larger lists from source websites
// Source sites: https://www.goodreads.com/quotes/tag/science, https://www.goodreads.com/shelf/show/must-read, https://projecteuler.net/archives
const quotes = [
  "“Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.”\n― Albert Einstein",
  "“The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.”\n― Isaac Asimov",
  "“The Seven Social Sins are:\n\nWealth without work.\nPleasure without conscience.\nKnowledge without character.\nCommerce without morality.\nScience without humanity.\nWorship without sacrifice.\nPolitics without principle.\n\n\nFrom a sermon given by Frederick Lewis Donaldson in Westminster Abbey, London, on March 20, 1925.”\n― Frederick Lewis Donaldson",
  "“Never memorize something that you can look up.”\n― Albert Einstein",
  "“One, remember to look up at the stars and not down at your feet. Two, never give up work. Work gives you meaning and purpose and life is empty without it. Three, if you are lucky enough to find love, remember it is there and don't throw it away.”\n― Stephen Hawking",
  "“If we knew what it was we were doing, it would not be called research, would it?”\n― Albert Einstein",
  "“Somewhere, something incredible is waiting to be known.”\n― Carl Sagan",
  "“The important thing is not to stop questioning. Curiosity has its own reason for existence. One cannot help but be in awe when he contemplates the mysteries of eternity, of life, of the marvelous structure of reality. It is enough if one tries merely to comprehend a little of this mystery each day.\n\n—\"Old Man's Advice to Youth: 'Never Lose a Holy Curiosity.'\" LIFE Magazine (2 May 1955) p. 64”\n― Albert Einstein",
  "“The fact that we live at the bottom of a deep gravity well, on the surface of a gas covered planet going around a nuclear fireball 90 million miles away and think this to be normal is obviously some indication of how skewed our perspective tends to be.”\n― Douglas Adams, The Salmon of Doubt: Hitchhiking the Galaxy One Last Time",
  "“The most beautiful experience we can have is the mysterious. It is the fundamental emotion that stands at the cradle of true art and true science.”\n― Albert Einstein, The World As I See It",
  "“Time is a drug. Too much of it kills you.”\n― Terry Pratchett, Small Gods",
  "“An expert is a person who has made all the mistakes that can be made in a very narrow field.”\n― Niels Bohr",
  "“I'm sure the universe is full of intelligent life. It's just been too intelligent to come here.”\n― Arthur C. Clarke",
  "“We are just an advanced breed of monkeys on a minor planet of a very average star. But we can understand the Universe. That makes us something very special.”\n― Stephen Hawking",
  "“Science and religion are not at odds. Science is simply too young to understand.”\n― Dan Brown, Angels & Demons",
  "“In the beginning there was nothing, which exploded.”\n― Terry Pratchett, Lords and Ladies",
  "“That which can be asserted without evidence, can be dismissed without evidence.”\n― Christopher Hitchens",
  "“Though my soul may set in darkness, it will rise in perfect light;\nI have loved the stars too fondly to be fearful of the night.”\n― Sarah Williams, Twilight Hours: A Legacy Of Verse",
  "“Everything must be made as simple as possible. But not simpler.”\n― Albert Einstein",
  "“A man who dares to waste one hour of time has not discovered the value of life.”\n― Charles Darwin, The Life & Letters of Charles Darwin",
  "“The good thing about science is that it's true whether or not you believe in it.”\n― Neil deGrasse Tyson",
  "“Heard melodies are sweet, but those unheard, are sweeter”\n― John Keats, Ode On A Grecian Urn And Other Poems",
  "“Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.”\n― Marie Curie",
  "“For me, I am driven by two main philosophies: know more today about the world than I knew yesterday and lessen the suffering of others. You'd be surprised how far that gets you.”\n― Neil deGrasse Tyson",
  "“Science is not only compatible with spirituality; it is a profound source of spirituality.”\n― Carl Sagan, The Demon-Haunted World: Science as a Candle in the Dark",
  "“Your assumptions are your windows on the world. Scrub them off every once in a while, or the light won't come in.”\n― Isaac Asimov",
  "“Space is big. You just won't believe how vastly, hugely, mind-bogglingly big it is. I mean, you may think it's a long way down the road to the chemist's, but that's just peanuts to space.”\n― Douglas Adams, The Hitchhiker's Guide to the Galaxy",
  "“If I have seen further it is by standing on the shoulders of Giants.”\n― Isaac Newton, The Correspondence Of Isaac Newton",
  "“If you wish to make an apple pie from scratch, you must first invent the universe.”\n― Carl Sagan, Cosmos",
  "“A thinker sees his own actions as experiments and questions--as attempts to find out something. Success and failure are for him answers above all.”\n― Friedrich Nietzsche",
];

const books = [
  "1984 (Kindle Edition)",
  "To Kill a Mockingbird (Paperback)",
  "The Book Thief (Hardcover)",
  "The Fault in Our Stars (Hardcover)",
  "Pride and Prejudice (Paperback)",
  "The Hunger Games (The Hunger Games, #1)",
  "The Elephant Tree (Paperback)",
  "Animal Farm (Mass Market Paperback)",
  "The Zombie Room (Kindle Edition)",
  "The Catcher in the Rye (Paperback)",
  "Fahrenheit 451 (Kindle Edition)",
  "Harry Potter and the Sorcerer's Stone (Harry Potter, #1)",
  "Gone Girl (Paperback)",
  "The Great Gatsby (Paperback)",
  "The Kite Runner (Paperback)",
  "Lord of the Flies (Paperback)",
  "The Alchemist (Paperback)",
  "The Diary of a Young Girl (Mass Market Paperback)",
  "Crime and Punishment (Paperback)",
  "One Hundred Years of Solitude (Mass Market Paperback)",
  "The Girl with the Dragon Tattoo (Millennium, #1)",
  "Brave New World (Paperback)",
  "Sapiens: A Brief History of Humankind (Paperback)",
  "Divergent (Divergent, #1)",
  "The Little Prince (Paperback)",
  "The Perks of Being a Wallflower (Paperback)",
  "The Girl on the Train (Hardcover)",
  "Sharp Objects (Paperback)",
  "Jane Eyre (Paperback)",
  "Man's Search for Meaning (Paperback)",
  "The Shining (Paperback)",
  "The Handmaid's Tale (The Handmaid's Tale, #1)",
  "Wuthering Heights (Paperback)",
  "The Picture of Dorian Gray (Paperback)",
  "Lolita (Paperback)",
  "Six of Crows (Six of Crows, #1)",
  "The Hobbit, or There and Back Again (Paperback)",
  "A Clockwork Orange (Paperback)",
  "The Count of Monte Cristo (Paperback)",
  "Thinking, Fast and Slow (Hardcover)",
  "Catch-22 (Paperback)",
  "And Then There Were None (Paperback)",
  "Anna Karenina (Paperback)",
  "Mistress Suffragette (Kindle Edition)",
  "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy, #1)",
  "Harry Potter and the Deathly Hallows (Harry Potter, #7)",
  "Shutter Island (Mass Market Paperback)",
  "Catching Fire (The Hunger Games, #2)",
  "Dark Places (Hardcover)",
  "Little Women (Paperback)",
];

const projects = [
  "https://projecteuler.net/problem=1",
  "https://projecteuler.net/problem=2",
  "https://projecteuler.net/problem=3",
  "https://projecteuler.net/problem=4",
  "https://projecteuler.net/problem=5",
  "https://projecteuler.net/problem=6",
  "https://projecteuler.net/problem=7",
  "https://projecteuler.net/problem=8",
  "https://projecteuler.net/problem=9",
  "https://projecteuler.net/problem=10",
  "https://projecteuler.net/problem=11",
  "https://projecteuler.net/problem=12",
  "https://projecteuler.net/problem=13",
  "https://projecteuler.net/problem=14",
  "https://projecteuler.net/problem=15",
  "https://projecteuler.net/problem=16",
  "https://projecteuler.net/problem=17",
  "https://projecteuler.net/problem=18",
  "https://projecteuler.net/problem=19",
  "https://projecteuler.net/problem=20",
  "https://projecteuler.net/problem=21",
  "https://projecteuler.net/problem=22",
  "https://projecteuler.net/problem=23",
  "https://projecteuler.net/problem=24",
  "https://projecteuler.net/problem=25",
  "https://projecteuler.net/problem=26",
  "https://projecteuler.net/problem=27",
  "https://projecteuler.net/problem=28",
  "https://projecteuler.net/problem=29",
  "https://projecteuler.net/problem=30",
  "https://projecteuler.net/problem=31",
  "https://projecteuler.net/problem=32",
  "https://projecteuler.net/problem=33",
  "https://projecteuler.net/problem=34",
  "https://projecteuler.net/problem=35",
  "https://projecteuler.net/problem=36",
  "https://projecteuler.net/problem=37",
  "https://projecteuler.net/problem=38",
  "https://projecteuler.net/problem=39",
  "https://projecteuler.net/problem=40",
  "https://projecteuler.net/problem=41",
  "https://projecteuler.net/problem=42",
  "https://projecteuler.net/problem=43",
  "https://projecteuler.net/problem=44",
  "https://projecteuler.net/problem=45",
  "https://projecteuler.net/problem=46",
  "https://projecteuler.net/problem=47",
  "https://projecteuler.net/problem=48",
  "https://projecteuler.net/problem=49",
  "https://projecteuler.net/problem=50",
];

// Returns a random number from 0 to the length of the passed arr - 1
const randNum = (list) => {
  let num = Math.floor(Math.random() * list.length);
  return num;
};

// Prints a random quote, book, and coding project from the predefined arrays above
console.log(
  `Quote of the day: ${quotes[randNum(quotes)]}\n\nBook of the day: ${
    books[randNum(books)]
  }\n\nProject of the day: ${projects[randNum(projects)]}`
);
